import React from 'react'
import Head from 'next/head'
import { LoginScreen } from 'features/LoginScreen'

const loginScreen = () => {
  return (
    
    <>
      <Head>
        <title>Netflix-clone</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      
      <div>
        <LoginScreen/>
      </div>
      
      </>
  )
}

export default loginScreen
